version: 2.1

jobs:
    build:
        docker:
            - image: cimg/go:1.14
              environment:
                GOLANGCI_LINT_VER:  1.24.0
        steps:
            - checkout
            - run: env | grep _VER | sort > /tmp/tools.ver
            - restore_cache:
                keys:
                    - v3-{{ checksum "/tmp/tools.ver" }}-{{ checksum "go.mod" }}-{{ .Branch }}
                    - v3-{{ checksum "/tmp/tools.ver" }}-{{ checksum "go.mod" }}-
                    - v3-{{ checksum "/tmp/tools.ver" }}-
            - run:
                name: Install tools
                command: |
                    cd /
                    golangci-lint --version | tee /dev/stderr | grep -wq $GOLANGCI_LINT_VER ||
                        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v$GOLANGCI_LINT_VER
                    which goveralls >/dev/null ||
                        go get -v github.com/mattn/goveralls
            - run: go test -mod=readonly -v -race ./...
            - run: golangci-lint run
            - run: goveralls -service=circle-ci -flags -tags=integration
            - save_cache:
                when: always
                key: v3-{{ checksum "/tmp/tools.ver" }}-{{ checksum "go.mod" }}-{{ .Branch }}
                paths:
                    - ~/go/bin/
                    - ~/go/pkg/
                    - ~/go/src/
                    - ~/.cache/go-build/
